//! Hierarchical Quadtree / Octree multi-level Level of Detail (LOD) generator.
//!
//! Organizes 64x64 voxel columns into hierarchical sections. Detail level 0 represents
//! 1:1 chunk resolution (4x4 chunks = 64x64 blocks per LOD section). Detail level L+1
//! is generated by 2x2 downsampling from level L.

use crate::heightmap::{ChunkVoxelGrid, ColumnVoxelPoint};
use crate::simd_blend::blend_8_colors;
use ahash::AHashMap;

/// A 64x64 column LOD section corresponding to a single Distant Horizons database entry.
#[derive(Debug, Clone)]
pub struct LodSection {
    /// Detail level (0 = full 1:1 chunk resolution, 1 = 2:1, 2 = 4:1, etc.).
    pub detail_level: u8,
    /// Section position X in detail-level grid units.
    pub pos_x: i32,
    /// Section position Z in detail-level grid units.
    pub pos_z: i32,
    /// Minimum height bounding coordinate.
    pub min_y: i16,
    /// Maximum height bounding coordinate.
    pub max_y: i16,
    /// 64 x 64 = 4096 columns (index: x * 64 + z).
    pub columns: Vec<Vec<ColumnVoxelPoint>>,
}

impl LodSection {
    /// Creates a blank LOD section initialized with 4096 empty column vectors.
    pub fn new_empty(detail_level: u8, pos_x: i32, pos_z: i32) -> Self {
        Self {
            detail_level,
            pos_x,
            pos_z,
            min_y: 0,
            max_y: 0,
            columns: vec![Vec::new(); 4096],
        }
    }

    /// Assembles Detail Level 0 LOD sections from a collection of `ChunkVoxelGrid` objects.
    pub fn build_level_0(chunks: &[ChunkVoxelGrid]) -> Vec<LodSection> {
        let mut section_map: AHashMap<(i32, i32), LodSection> = AHashMap::new();

        for chunk in chunks {
            let sec_x = chunk.chunk_x >> 2;
            let sec_z = chunk.chunk_z >> 2;
            let chunk_rel_x = (chunk.chunk_x & 3).rem_euclid(4) as usize;
            let chunk_rel_z = (chunk.chunk_z & 3).rem_euclid(4) as usize;

            let section = section_map
                .entry((sec_x, sec_z))
                .or_insert_with(|| LodSection::new_empty(0, sec_x, sec_z));

            if chunk.min_y < section.min_y || section.min_y == 0 {
                section.min_y = chunk.min_y;
            }
            if chunk.max_y > section.max_y {
                section.max_y = chunk.max_y;
            }

            for cz in 0..16 {
                for cx in 0..16 {
                    let col_idx = cx + cz * 16;
                    let block_x = chunk_rel_x * 16 + cx;
                    let block_z = chunk_rel_z * 16 + cz;
                    let grid_idx = block_x * 64 + block_z;

                    section.columns[grid_idx] = chunk.columns[col_idx].points.clone();
                }
            }
        }

        section_map.into_values().collect()
    }

    /// Downsamples up to 4 child sections of detail level L into 1 parent section of level L+1.
    pub fn downsample_from_children(
        parent_detail_level: u8,
        parent_pos_x: i32,
        parent_pos_z: i32,
        children: &[&LodSection],
    ) -> LodSection {
        let mut parent = LodSection::new_empty(parent_detail_level, parent_pos_x, parent_pos_z);

        for child in children {
            if child.min_y < parent.min_y || parent.min_y == 0 {
                parent.min_y = child.min_y;
            }
            if child.max_y > parent.max_y {
                parent.max_y = child.max_y;
            }

            let rel_child_x = (child.pos_x & 1).rem_euclid(2) as usize;
            let rel_child_z = (child.pos_z & 1).rem_euclid(2) as usize;

            // Child 64x64 is downsampled 2x2 into parent 32x32 quadrant
            for pz in 0..32 {
                for px in 0..32 {
                    let c_x0 = px * 2;
                    let c_z0 = pz * 2;

                    let c00 = child.columns[c_x0 * 64 + c_z0].as_slice();
                    let c01 = child.columns[c_x0 * 64 + (c_z0 + 1)].as_slice();
                    let c10 = child.columns[(c_x0 + 1) * 64 + c_z0].as_slice();
                    let c11 = child.columns[(c_x0 + 1) * 64 + (c_z0 + 1)].as_slice();

                    let merged = downsample_2x2_columns(&[c00, c01, c10, c11]);

                    let out_x = rel_child_x * 32 + px;
                    let out_z = rel_child_z * 32 + pz;
                    parent.columns[out_x * 64 + out_z] = merged;
                }
            }
        }

        parent
    }
}

/// Downsamples a 2x2 neighborhood of vertical columns into consolidated point runs.
fn downsample_2x2_columns(cols: &[&[ColumnVoxelPoint]]) -> Vec<ColumnVoxelPoint> {
    let mut all_points: Vec<&ColumnVoxelPoint> = Vec::new();
    for c in cols {
        for pt in *c {
            all_points.push(pt);
        }
    }

    if all_points.is_empty() {
        return Vec::new();
    }

    let mut min_y = i16::MAX;
    let mut max_y = i16::MIN;
    let mut colors = [0u32; 8];
    let mut sample_count = 0;
    let mut rep_name = String::new();
    let mut rep_flags = 0;

    for pt in all_points {
        if pt.y_min < min_y {
            min_y = pt.y_min;
        }
        if pt.y_max > max_y {
            max_y = pt.y_max;
        }
        if sample_count < 8 {
            colors[sample_count] = pt.color;
            sample_count += 1;
        }
        if rep_name.is_empty() {
            rep_name = pt.block_name.clone();
            rep_flags = pt.flags;
        }
    }

    let blended_color = blend_8_colors(&colors);

    vec![ColumnVoxelPoint {
        y_min: min_y,
        y_max: max_y,
        color: blended_color,
        block_name: rep_name,
        flags: rep_flags,
    }]
}
